name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: model.tex
          working_directory: tex/
      - name: Upload file
        uses: actions/upload-artifact@master
        with: 
          name: model
          path tex/